### ISSUE TITLE
Make the plugin manifest paths in the policy file be paths to the plugin discovery manifest

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#612]
Just caught this inconsistency between RFD4 and the current implementation. The RFD says:

> (Named Attribute) Manifest (Optional / String): The download location of the plugin discovery manifest for this plugin. Until a plugin registry is established for Hipcheck plugins, this attribute will effectively be required, as otherwise Hipcheck will have no mechanism to discover the location of the download metadata for a plugin.

However, the current implementation makes the _manifest_ key/value point to the plugin manifest, not to the discovery manifest. This needs to be fixed in advance of shipping 3.8, though we can proceed shipping v0.1 of the plugins on Monday.

**Comment by j-lanson** [comment]
In my understanding, the way we've done it is as follows: 

If the `manifest` field can be parsed as a URL, then we treat it as a download manifest URL. Otherwise, if it can be parsed as a local path, we treat it as the path to a local plugin manifest file. You can see this in `plugin/retrieval.rs` - `retrieve_plugin_from_network` has a two-stage process, where `retrieve_local_plugin` does not. 

Pointing `manifest=` to a local path is specific to local testing, where you're going to be using locally-built binaries, in which case involving a download manifest would be nonsensical.
