### ISSUE TITLE
Refactor CLI for `check` args

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#94]
Right now, we have a bunch of subcommands for `hc check` to specify the specific type of object being checked. Instead, it would be nice to have something like the following:

```sh
$ hc check [-t/--target = "<TYPE>"] <TARGET>
```

So it might look like the following:

```sh
$ hc check -t npm express                         # specified as an NPM package
$ hc check pkg:npm/express                        # inferred as an NPM package
$ hc check my-package.spdx                        # inferred as a text-format SPDX file
$ hc check https://github.com/expressjs/express   # explicit GitHub repo
$ hc check pkg:github/expressjs/express           # Package URL GitHub repo
```

Basically, it can be an explicit URI, a Package URL, or a package name. Package names require a type, so we know what package host it's on.

---

## Compatibility

The prior format will need to be preserved to avoid breaking compatibility, but we should hide it in the help text and encourage people to transition to the new format.

**Comment by j-lanson** [comment]
This looks like a clean solution right now because every subcommand takes just 1 positional string arg. It might get messier if this fact changes. 

Also, I don't know that we can inject custom pattern matching in `clap derive`, so we'd have to detect if this is a "new" invocation, then do external pattern matching on the string / detection of the `-t` value and then reconstruct the appropriate `<Type>Args` struct from the collected variadic args.

Is there any chance of each subcommand having additional custom commands in the future?
